#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

#Check Root
[ $(id -u) != "0" ] && { echo "Error: You must be root to run this script"; exit 1; }

echo "1.服务器控制"
echo "2.用户管理"
echo "3.全局流量管理"
echo "4.实验性功能"
echo "5.程序自检"
echo "6.denyhosts设置"
echo "7.生成20个用户"


while :; do echo
	read -p "请选择： " choice
	if [[ ! $choice =~ ^[1-7]$ ]]; then
		echo "输入错误! 请输入正确的数字!"
	else
		break	
	fi
done

if [[ $choice == 1 ]];then
	bash /usr/local/jluee/server.sh
fi

if [[ $choice == 2 ]];then
	bash /usr/local/jluee/user.sh
fi

if [[ $choice == 3 ]];then
	bash /usr/local/jluee/traffic.sh
fi

if [[ $choice == 4 ]];then
	bash /usr/local/jluee/dev.sh
fi

if [[ $choice == 5 ]];then
	bash /usr/local/jluee/self-check.sh
fi

if [[ $choice == 7 ]];then
	cp /usr/local/jluee/usergenerate.py /usr/local/shadowsocksr
	cd /usr/local/shadowsocksr
	python /usr/local/shadowsocksr/usergenerate.py
	cd /root
fi